# Generated by Django 3.0 on 2020-04-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledSettings', '0002_auto_20200409_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='brightness',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='speed',
            field=models.IntegerField(),
        ),
    ]
