# Generated by Django 3.0 on 2020-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledSettings', '0003_auto_20200409_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='turn_off_time',
            field=models.IntegerField(),
        ),
    ]
