# Generated by Django 3.0 on 2020-04-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledSettings', '0004_auto_20200409_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='turn_off_time',
            new_name='timeout',
        ),
    ]
