# Generated by Django 3.0 on 2020-04-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledSettings', '0007_remove_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
