# Generated by Django 3.0 on 2020-05-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledSettings', '0008_remove_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='color',
        ),
        migrations.AddField(
            model_name='profile',
            name='blue',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='green',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='red',
            field=models.IntegerField(default=0),
        ),
    ]
